version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/client"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
