version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/client"
      - "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "WCY-dt"
    ignore:
      - dependency-type: "development"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "WCY-dt"